### ISSUE TITLE
Support Logging Paths and Query Params

### ISSUE THREAD

**Issue by sh4t** [cgiffard/node-simplecrawler#118]
I am looking to give simple crawler a test in a lab environment and I am curious if it spiders and logs query parameters for a given uri path/resource. 

For example if it finds a form on a page, will it log the page and the fields it found by their html ID entity? 

If it finds a search page, with a search input field with and ID of search and say a drop down for date, log the page and the query fields:

/search?search=something&date=month

**Comment by cgiffard** [comment]
No, but that's because the default discovery function is quite rudimentary and doesn't parse HTML — it does a naive best-effort scan of the page for things that look like URLs, and queues them up.

It is possible to do this, however: you could easily use node-simplecrawler with cheerio and provide your own URL discovery function. [You can do so as documented here.](https://github.com/cgiffard/node-simplecrawler#waiting-for-asynchronous-event-listeners)

Please feel free to comment here if you need any help realising this!
