### ISSUE TITLE
simplecrawler goes beyond the set level of depth

### ISSUE THREAD

**Issue by shekarls** [cgiffard/node-simplecrawler#128]
Hi,
  When i set maxdepth = 0, I am expecting that only links in the current page will be parsed for http response, but for my suprise ,  it crawls thru multiple pages apart from the current page.

Is my implementation in sync with whats expected.

var Crawler = require("../lib");
Crawler.initialProtocol = "https";
Crawler.maxDepth = 0;

var url = "https://www.rediff.com";

Crawler.crawl(url, function(queueItem) {

console.log("Completed fetching resource:",queueItem.url);
});

****************************************************************************************************************
Also can you provide me a code snippet how to check if the links are "200 ok"

I tried this, it doesnt work for me.

myCrawler.on("fetchheaders", function(queueItem, responseObject) {
	console.log(queueItem.url);
	console.log(responseObject.statuscode);

});
	myCrawler.start();

******************************************************************************************************************

Also, how to use fetch404 , is the below way would print 404 urls

myCrawler.on("fetch404", function (queueItem, response )  {
	console.log(queueItem.url);
});

*******************************************************************************************************************

**Comment by cgiffard** [comment]
Hi @shekarls —

The 404 method you have is correct.

The way to retrieve the status code is to get the `queueItem.stateData.code`. I urge you to read the documentation, especially this part: https://github.com/cgiffard/node-simplecrawler#queue-items

In regards to the depth — please update your version of simplecrawler. The previous version would fetch one level deeper in order to retrieve resources, which was confusing. This version does what it says on the tin.
