### ISSUE TITLE
Crawling with Promises

### ISSUE THREAD

**Issue by russelltaylor05** [cgiffard/node-simplecrawler#181]
Would it be possible to use Simple Crawler as part of a Promise chain? I've used Bluebird before to Promisify things, but not sure if it would work with this crawler.

**Comment by fredrikekelund** [comment]
Not really. Promises are meant as a replacement for callbacks, but simplecrawler is event driven, not callback driven. Using callbacks to any greater extent in simplecrawler wouldn't make much sense, since the developer normally needs to react more than once to what happens in simplecrawler. [request](https://www.npmjs.com/package/request) for example is different, promisification makes sense there as it performs a single operation with a single expected result.

I have very little experience with functional reactive programming, but that might be a better alternative and more in line with what you're looking for. If I were to try and apply those concepts to simplecrawler, I would look to eg. [bacon.js](http://baconjs.github.io/) ("it's the _ of Events"). FRP takes streams of data and transforms it, normally using observables to put that data somewhere, I believe.

**Comment by cgiffard** [comment]
[Events can be chained in pretty ways similar to promises anyway, and are nice and composable.](https://github.com/cgiffard/SteamShovel/blob/master/lib/cli.js#L19-L29) :)

Thanks @fredrikekelund
