### ISSUE TITLE
Method to de-qeuque item

### ISSUE THREAD

**Issue by rolfen** [cgiffard/node-simplecrawler#188]
This is a feature request.
I think there should be a way to deQueue an item. I did not find a dequeue method.
This would be either crawler.dequeue(queueItem) or queueItem.dequeue() 
Or maybe something else?

**Comment by bfwg** [comment]
What is the purpose of dequeue?

**Comment by rolfen** [comment]
In some cases, we don't want to queue an item but based on some more advanced conditions, and before actually fetching the item.
It also makes sense since there is a queue method to have a way to revert that operation.
At the moment I am using the discovery function for that.

**Comment by cgiffard** [comment]
You can already prevent items from being queued, without having to undo the operation. Check the section on [Fetch Conditions](https://github.com/cgiffard/node-simplecrawler#excluding-certain-resources-from-downloading) in the docs. :)

Please let me know if this isn't clear — and I'll try to add some more explanation.

**Comment by rolfen** [comment]
It's clear thanks. Fetch conditions only allows me to check against URL.
I wanted to check queue depth before deciding, and that was the origin for this idea.
If addFetchCondition callback would accept something such as a queueItem object or something more advanced than a URL, it might be helpful.

**Comment by cgiffard** [comment]
What else apart from depth would be useful? (Remember that there's only limited information available before fetching an item.)

**Comment by fredrikekelund** [comment]
@rolfen it's already possible to check queue depth in fetch conditions, see [this section of the README](https://github.com/cgiffard/node-simplecrawler#adding-a-fetch-condition).

The same issue was discussed in #256 and the decision was to not add a remove method for now, since this might make the API more confusing - we want people to filter stuff before it's added to the queue, not after.

Please leave a comment if you still believe there's a good use case for a queue.remove method!
