### ISSUE TITLE
Crawler ignores "HTML redirects"

### ISSUE THREAD

**Issue by rolfen** [cgiffard/node-simplecrawler#190]
Example:

     <meta http-equiv="refresh" content="0; url=en/index.html">

My crawler ignores that, and I don't find any code to handle it. I'm going to have to extend the discovery function (again).

**Comment by cgiffard** [comment]
Thanks for reporting that. I'll add an expression to the discovery function.

**Comment by gorbatenkov** [comment]
+1 for this feature

**Comment by rolfen** [comment]
I wrote a quick extension to the discovery function, using cheerio to match meta tags that have attributes http-equiv and content, then use this regex:  /^\s*url\s*=\s*(.+)$/i  to extract the URL.
I don't think it can be done properly with a regex only.
Anyway, thought this might help. If I have time maybe I can try to fork and extend the crawler - if you would consider my pull request afterwards!

**Comment by gorbatenkov** [comment]
Hello, will you modify discovery function of the crawler? I think this feature will be very helpfull

**Comment by gorbatenkov** [comment]
Hello,  rolfen, can you share your decision with me?

**Comment by rolfen** [comment]
Hello gorbatenkov. Here is my code. I don't know if it will work in your context. Hoping it will be useful.
It has a dependency for npm module cheerio.
```
    // wrap default discovery function with a depth check
    var defaultCrawlerResourceDiscoveryFunction = crawler.discoverResources;
    crawler.discoverResources = function(buf, queueItem) {
        var buffer = buf.toString("utf8");
        var ret = defaultCrawlerResourceDiscoveryFunction.call(crawler, buf, queueItem);
        if(buffer.toLowerCase().indexOf('refresh')) {
            // do we have HTML refresh? Crawler does not understand it.
            var $ = cheerio.load(buffer);
            var httpRedirects = $('meta[http-equiv]');
            if (httpRedirects.length > 0) {
                Object.keys(httpRedirects).forEach(function(key){
                    if(!isNaN(key) && (typeof httpRedirects[key].attribs['content'] !== 'undefined')) {
                        var valAttrParts = httpRedirects[key].attribs['content'].split(';');
                        valAttrParts.forEach(function(attrPart){
                            var matches = attrPart.match(/^\s*url\s*=\s*(.+)$/i)
                            if(matches && matches.length > 1) {
                                ret.push(matches[1]);
                            }
                        });
                    }
                });
            }
        }

        return ret;
    };

```

**Comment by gorbatenkov** [comment]
Thank you rolfen.

**Comment by cgiffard** [comment]
Generally speaking the simplecrawler philosophy is that the discovery mechanism is almost painfully stupid — it's a brute-force kind of approach where it'll try match *everything*, even if it isn't really a URL — and uses filters to pull out all the garbage after the fact.

The idea is that a whole bunch of 404s for junk resources are less of a problem than missing something — if your needs are the inverse of this, you'll need to tune the discovery function. Because of this, simplecrawler can do crazy things like look inside binary files for URLs — the tradeoff being that it picks up a bit of junk.

When discovery needs get a lot more sophisticated, everybody has really different requirements — (and to a large extent this is true in a lot of places... I've seen the simplecrawler filtering API balloon out to a considerable size because everybody needs different ways of filtering the resources they download.) Rather than the hassle of supporting every case, it should be easy to *replace or augment* simplecrawler's own discovery mechanisms with your own. I would prefer not to take an opinionated approach and bundle cheerio or other weighty dependencies such as jsdom or phantom.

If there are ways we can make simplecrawler's discovery mechanism easier to augment, let me know!

In regards to this issue, I'd prefer to keep it a dumb regex for now, and see how far we get. :)

**Comment by rolfen** [comment]
Hello cgiffard. Thanks for your answer.

I don't advocate cheerio and it should be easy to avoid it. I just copy-pasted my solution in this particular case on request and hoping it might help somebody. I wrote this code under pressure and in like 1/2 hour. It is not properly commented, and looking at it, in all honesty looks like terrible code.

The core issue here is that a crawler is expected, I believe, by most users, to handle HTML refresh, as it does already handle HTTP redirects.
This is the behaviour of browsers, which can be useful as a reference I believe, when in doubt.

Keeping in mind my belief that following HTML refresh is the expected behaviour; Maybe if you just mention this peculiarity in the documentation, then it would be OK.

I trust you and have no interest nor will to argue on wider philosophical or technical consideration for simplecrawler otherwise, but thank you for your explanation.

And by the way thank you for this nice software.

**Comment by cgiffard** [comment]
Thanks again @rolfen — just wanted to quickly chime in to say that I wasn't critiquing your code or anything, (I really appreciate you contributing to discussions and helping out here!) — just wanted to elaborate on what simplecrawler's discovery mechanism is about. :)

I do think we should support meta refresh, as well as the equivalent HTTP header (which we currently don't) — and tags like `<base>`, etc., so I'll be taking your advice into consideration. :)
