### ISSUE TITLE
Calling crawler.stop() does not stop the crawling process 

### ISSUE THREAD

**Issue by andreivisan** [cgiffard/node-simplecrawler#206]
I would like to be able to stop the crawler manually. I tried by calling crawler.stop() but nothing happens. Am I doing it wrong?

**Comment by cgiffard** [comment]
`Crawler.stop()` halts the timer which spawns new requests, but it doesn't halt requests already in flight. If your crawler is configured to be highly concurrent, or the latency of the requests in flight is high, the crawler may take a while to finally die.

Could you offer some more detail about your situation? Perhaps I can assist in troubleshooting? What have you observed?

**Comment by andreivisan** [comment]
Thank you for your fast reply. I finally understand now why it didn't stop :).

I have built a web crawler with a UI as well. So what I am trying to do is to start a crawler instance (1 thread) for a certain URL I provide and I would like to have the option to stop it manually from the UI. So when I hit the "Stop" button I would like to send an event (maybe "complete" or "fetchcomplete") so that the crawler stops.

I tried to send both of the above events but it still didn't stop. Should I provide some code as well?

**Comment by andreivisan** [comment]
Can anybody please help me with this issue? I would like to be able to stop the crawler manually.

**Comment by fredrikekelund** [comment]
@andreivisan I'm not sure I understand - does calling the stop method not work at all in your case? Or do you need to very specifically halt the crawler with all of its currently open requests?

**Comment by andreivisan** [comment]
@fredrikekelund thank you for your answer. I need to very specifically halt the crawler with all of its currently open requests.

**Comment by cgiffard** [comment]
There's no easy API for stopping all open requests at this stage, unfortunately. It might be worth storing the open requests against the crawler so they can be individually addressed (and aborted.)

**Comment by andreivisan** [comment]
Thank you for your reply. I will try and do what you suggested, store each individual open request then abort them one by one.

**Comment by fredrikekelund** [comment]
@andreivisan if you find a way to implement it nicely, feel free to submit a pull request. One way, although slightly hacky, might be to monkey patch the `http.request` and `https.request` methods to catch every request that is initiated.

**Comment by andreivisan** [comment]
@fredrikekelund thank you for your answer. If I will find an elegant solution I will submit a pull request.

**Comment by cgiffard** [comment]
The crawler already uses a counting mechanism to maintain a constant level of concurrency — it'd be a no brainer to extend that to actually hold the requests inside an array, for instance, and use the length of that array rather than a plain integer for managing concurrency.

BTW @fredrikekelund I added you to the npm owners. :)

**Comment by fredrikekelund** [comment]
@cgiffard golden, thanks! :100:

**Comment by tmpfs** [comment]
From my point of view cancelling in-flight requests when `stop()` is called should be beyond the scope of `simplecrawler` if an implementor really needs that functionality they could do it by listening for `fetchheaders` and tracking the requests on `fetchcomplete` they could clean the tracked in-flight request, when `stop()` is called abort the in-flight requests.

I have just tested `stop()` and from my perspective it works correctly, however what I would like to see for consistency and flow of my code is a `crawlstop` event emitted, could a PR for this be merged?

I can see `crawlstop` being implemented very easily with an additional test case and no breaking changes.

**Comment by fredrikekelund** [comment]
@tmpfs a "crawlstop" event sounds like a good idea, makes a lot of sense to me!

I'm not sure I find it beyond the scope of simplecrawler to stop requests mid-flight. I understand the need for it, and it should be fairly simple to implement. I do however think that there might be a need for the current behavior as well: the developer might want the open requests to be completed before exiting the process or whatever.

So a suggestion would be to let the developer pass a single boolean parameter to `crawler.stop` that determines whether to abort all requests at once or not (default would be not to). Moreover, we would add a "crawlstop" event that would fire when all requests have ended, so either instantaneously if I pass `true` to `crawler.stop`, or after a little while if I pass nothing or a faulty value.

Thoughts?

**Comment by tmpfs** [comment]
That sounds fine to me, I think if you add it then it would be useful to me if it were optional, ie, the behaviour remains as it is now and an `abort` parameter can be passed such that the signature becomes:

```javascript
function stop(abort)
```

As you suggest :)

As an aside, I haven't seen it in the docs but I noticed there is a `crawler.running` boolean, can that be considered public and safe to use? Save me maintaining a `paused` flag ;)

Ah, I would like `crawlstop` to fire when `stop()` is called for consistency with the behaviour of `crawlstart` (there is no delay), maybe we need a separate event when all the in-flight requests have been closed, `crawlstopped` maybe - for want of a better name ;)

**Comment by tmpfs** [comment]
Or maybe even cleaner just pass a callback to `stop`:

```javascript
function stop(abort, cb)
```

There are quite a few events already ;)

**Comment by fredrikekelund** [comment]
I thought about the callback solution, but I'm a bit hesitant towards it, simply because we rely so heavily on events elsewhere. Using a callback seems to break the convention. 

I believe the `running` flag is safe to use publicly. 

Hmm, could you expand a bit on why you'd want `crawlstop` to fire immediately? To me it seems hard to argue consistency with `crawlstart`, simply because there naturally isn't any delay to starting the crawler, but for the crawler to be truly stopped, there is. Just trying to make sense of the best solution here :)

**Comment by tmpfs** [comment]
@fredrikekelund, you are correct on both points. It does not make sense to use a callback approach when the library uses events primarily. A callback also prevents easily registering multiple functions for the event.

I was stupidly thinking about the flow of my code rather than the best logic for simplecrawler with regard to `crawlstop`; your suggestion feels right to me.

We should also consider the `running` variable and how it is handled, I guess it makes sense when `abort` is not specified to immediately set it to `false` but when aborting in-flight requests only set to `false` when they have all been cancelled - sound reasonable? That would mean effectively that `running` is set to `false` when `crawlstop` fires.

Also, what about resuming after a stop, are aborted requests left in the queue their `status` reset so that when `start()` is called again they would be loaded, I would assume so.

**Comment by fredrikekelund** [comment]
So I think we have a good plan of action here! `crawler.stop` takes a single boolean parameter that makes the crawler immediately fire `crawlstop` as well asabort all requests in flight if true. If false, it waits for all requests to complete before firing `crawlstop` and effectively quitting.

I think it'd be alright to let the `crawler.running` property be set to false as soon as `crawler.stop` is called, the current stopping logic depends on it.

@tmpfs we're pushing for a 1.0 release this Sunday, do you have time to submit a PR for this in the next few days? Otherwise I'll try to have a look. It doesn't *have* to be in 1.0, but it'd be nice

**Comment by tmpfs** [comment]
@fredrikekelund,

Sounds like a good plan, bit busy for the next couple of days but could look at it around Thursday.

Let me know how you want to proceed.

**Comment by fredrikekelund** [comment]
I won't be able to look into it before Thursday anyway, so that sounds good! We can see on Saturday how it's coming along and whether it seems reasonable to include it in 1.0

**Comment by cgiffard** [comment]
I'm actually going to attack this one now, and see if I can get it resolved relatively quickly. Let me know if you're already some ways into it and wanna take this one back off my hands, @tmpfs!

**Comment by tmpfs** [comment]
Ah, sorry not yet completed my current work. The commit looks good at a glance.

I'll upgrade once 1.0 is released and take if for a spin.
