### ISSUE TITLE
Have crawler follor redirect Http 301

### ISSUE THREAD

**Issue by perrohunter** [cgiffard/node-simplecrawler#208]
Hi,
The crawler is hitting urls which were permanently moved and return status 301 on the fetcherror event.

Is there a way to have the crawler follow the redirect to the new location?

**Comment by cgiffard** [comment]
Hi — thanks for filing an issue.

[The code in question should respect any 3XX response which sets a location header](https://github.com/cgiffard/node-simplecrawler/blob/master/lib/crawler.js#L1184-L1185)

Can you post a test case or some code which shows the problem? Could the server not be setting a `Location` header? Perhaps the redirect is to a hostname which is not whitelisted by your initial configuration?

**Comment by tibetty** [comment]
I tried but the hang-up issue is still there... Really appreciate your quick response though!

**Comment by fredrikekelund** [comment]
@tibetty do you mean the issue from #214? Would be nice if we could keep that discussion in that thread, you can still comment there, even if the ticket is closed. I'll go ahead and reopen it in any case

**Comment by fredrikekelund** [comment]
If you're still having trouble with this, feel free to open a new issue, @perrohunter, but it's not unlikely that the problem doesn't lay with simplecrawler not following redirects (could maybe be due to some header not being sent or something similar - see #228 for a recent fix related to default header)
