### ISSUE TITLE
addFetchCondition()

### ISSUE THREAD

**Issue by rdonmez** [cgiffard/node-simplecrawler#211]
how can I add a condition from mongodb?
thanks.

**Comment by bfwg** [comment]
This is how you add a condition.
```js
crawler.addFetchCondition((url) => {
    var mongodbCondidtion = 'whatever';
   // do something with url and condidtion
    if (mongodbCondidtion)
      return true;
    else
      return false;
  });
```
Cheers

**Comment by rdonmez** [comment]
no crawling when I use mongo query callback function. the process doesn't continue. 

here is my code.

crawler.addFetchCondition(check);
function check (url) {
    queue_item.findOne({ host: url.host }, function (err, doc) { 
        return doc != null;
    });
}

**Comment by cgiffard** [comment]
The fetch condition is currently a *synchronous* API, whereas the Mongo query you're running is an *asynchronous* API. If you're stuck, it might help to read through [this great resource on asynchronous programming in JS](https://github.com/getify/You-Dont-Know-JS/tree/master/async%20%26%20performance).

Firstly, you can't return from an asynchronous API. The function has long since returned in this case — and passed `null` to the caller. This is evaluated to be `false` by simplecrawler, and since it matches every URL, nothing at all will be fetched.

I'm thinking we should probably allow an async API in fetch conditions to allow this kind of use case. However, in the mean time, it's best to fetch the list of URLs which should be fetched, and store them locally in the VM in a way they can be accessed *synchronously*.

**Comment by fredrikekelund** [comment]
I'll close this for now, if we go on to implement an asynchronous fetch condition API, I'll open a dedicated ticket for that and reference this one. Let us know if you have any more problems @rdonmez!
