### ISSUE TITLE
Strange javascript resources

### ISSUE THREAD

**Issue by tmpfs** [cgiffard/node-simplecrawler#232]
Just logging this before I filter them out from my crawl:

```
 WARN | 404 http://localhost:3000/assets/js/vendor/%29.revokeObjectURL%28file
 WARN | 404 http://localhost:3000/assets/js/vendor/blob
 WARN | 404 http://localhost:3000/assets/js/vendor/%29.createObjectURL%28blob
```

Generated by this file:

https://github.com/eligrey/FileSaver.js/blob/master/FileSaver.js

It appears to me that possibly this is an error with the discover resources logic for javascript files.

**Comment by fredrikekelund** [comment]
@cgiffard's philosophy has been to keep simplecrawler's discovery mechanism "dumb", with the reasoning that it's better for the crawler to make a few junk requests than for it to miss some stuff. So by default, the `discoverResources` method will pick up some garbage, the idea is to make it easy to replace this logic with more a more advanced discovery function, tailored for the dev's specific needs.

If there is a specific, non-huge improvement to one of the default discoverRegex's, feel free to submit a PR, otherwise, maybe the way to go in your case would be to override the discoverResources method? When I've worked with simplecrawler, I've had a lot of success using cheerio to parse pages and do a more refined extraction of resources!

**Comment by tmpfs** [comment]
Thanks, I just got a feel for that from reading the `base href` issue.

Now I have my pattern matching support in place, it's pretty easy for me to ignore these sorts of things without implementing `discoverResources`.

Cheers for the tip on `cheerio`, looks quite nice :)

Closing as expected behaviour.

**Comment by tmpfs** [comment]
For the record it looks like these patterns:

```
        /\s?url\((["']).*?\1\)/ig,
        /\s?url\([^"'].*?\)/ig,
```

For CSS I imagine, I think we could remove the `i` flag and be safe, it then wouldn't match the junk in this issue and I don't know of anyone that uppercases `url()` in CSS files and likely uppercase is invalid CSS anyhow (I would have to check).

What do you think?

**Comment by tmpfs** [comment]
Spec is quite specific:

https://www.w3.org/TR/CSS2/syndata.html#uri

I know css selectors are case-insensitive but I think we could be safe to remove those `i` flags, @cgiffard - what do you think?

**Comment by tmpfs** [comment]
Just confirmed that removing the `i` flag does indeed prevent those junk requests.

**Comment by cgiffard** [comment]
There are actually lots of inline JS scripts around which have code like `openURL("http://foo/bar.txt")`. That regex is designed to catch those — the philosophy being that overly broad matching (and then filtering) is better than missing resources.

It was fascinating to see the outcome of this philosophy at work when scanning inside binary files (like Microsoft Office documents) actually yielded real URL results that wouldn't have been found otherwise (and a whole lot of junk, but I figured it was a reasonable tradeoff.)

I'm inclined to leave the regex match as it is, but I'd welcome discussion.

**Comment by tmpfs** [comment]
That's fine with me, thanks for the clarification.

Would it not make sense then for `simplecrawler` to provide some `discoverResources` strategies rather than have developers constantly re-inventing the wheel? These could be external npm packages.

For example, I think my use case is likely the most common, I am only interested in valid links within the HTML and CSS documents.

Question: what would be the best way to disable discovering resources in javascript files without writing a custom `discoverResources`?

**Comment by tmpfs** [comment]
Or alternatively a separate pattern for the scenario you describe and then expose an API for modifying (adding and deleting) from the default list of patterns?

That would solve this issue for me without the need to write `discoverResources` which seems like overkill for this scenario.

**Comment by tmpfs** [comment]
Maybe named patterns in an object that is later flattened to an array?

**Comment by cgiffard** [comment]
Good suggestion, and please feel absolutely welcome to provide a `discoverResources` function that can be published as an external module. Then you could do something as simple as:

```js
crawler.discoverResources = require("nice-link-discovery");
```

(Or similar.)

**Comment by fredrikekelund** [comment]
> Or alternatively a separate pattern for the scenario you describe and then expose an API for modifying (adding and deleting) from the default list of patterns?

Maybe I'm misunderstanding what you mean here, but the `discoverRegex` array is public and documented, so operating on that array would be the API for modifying the list of discovery patterns :)

> Question: what would be the best way to disable discovering resources in javascript files without writing a custom discoverResources?

`crawler.supportedMimeTypes` and `crawler.downloadUnsupported` can be used to avoid downloading javascript resources. If you'd rather download the files, but not look for resources in them, you could either listen for the `discoverycomplete` event, check the queueItem's Content-Type and mutate the resources array as you want, or you could monkey patch the discoverResources method with a method that only calls the original method when the Content-Type is the one you want, or you could swap out the entire discoverResources method (it's quite a simple method, really).

**Comment by cgiffard** [comment]
It's my preference to consider the current code complete for this use case, so I'm closing this issue. Feel free to reopen it if you vehemently disagree. :)

**Comment by tmpfs** [comment]
No worries for me, I'll implement `discoverResources` (later). Thanks for your time.
