### ISSUE TITLE
Can't crawl petflow.com

### ISSUE THREAD

**Issue by moshewe** [cgiffard/node-simplecrawler#242]
Hi all,

I'm trying to crawl petflow, specifically [minichunks](https://www.petflow.com/product/iams/iams-proactive-health-adult-minichunks-dry-dog-food). I turned on all event listeners, and all I'm getting is crawl started, then queuing my url, then started fetch - and from then on an endless stream of `complete` events.

First site I've had any trouble crawling... At first, I thought it's the user agent, but the endless `complete`s raised some doubts. Any thoughts?

**Comment by cgiffard** [comment]
That's the first I've heard of such a behaviour. How are you instantiating the crawler?

**Comment by moshewe** [comment]
This is the exact code:

    var target = 'http://www.belk.com/AST/Main/Belk_Primary/PRD~8100331SIGNA8328T4/Le+Creuset+Signature+5+qt++Oval+French+Oven.jsp'

    var crawler = Crawler.crawl(target);
    crawler.decodeResponses = true;
    crawler.maxDepth = 1
    /*event listeners*/
    crawler.start();

I'll next try to `Crawler.crawl(target)`. I thought both of these instantiations would be identical in result...

**Comment by fredrikekelund** [comment]
It looks like you're starting the crawler twice, which would register two intervals that trigger new page fetches. Since only the ID of the first interval is saved, when the crawler has completed and that interval is cleared, there will still be another one asking the crawler to fetch new pages, and the crawler will respond with emitting a complete event since there aren't any new pages to fetch. So basically: if you're instantiating the crawler with the quick method, you shouldn't call `crawler.start`.

It's a fair point that maybe the `start` method shouldn't do anything if the crawler is already running, though. I'll open a dedicated ticket for that and close this one. Let us know if this didn't solve your problem!

**Comment by moshewe** [comment]
Thanks! It worked for me until now, that's why I was so confused!
