### ISSUE TITLE
Use node-simplecrawler client-side, in the browser

### ISSUE THREAD

**Issue by hristod** [cgiffard/node-simplecrawler#250]
Is it possible? Can I use node-simplecrawler with browserify or Webpack on the client side? I'd like to use the users to crawl the websites and pass the data to a server ...

**Comment by fredrikekelund** [comment]
I haven't actually tried using simplecrawler on the client, but even though it should be technically possible - there are no disk writes per default, and the HTTP requests should be translatable to XHR requests - it is likely to fail for most sites since browser CORS policies will prevent XHR requests from one domain to another unless explicitly allowed by the server. Of course, that doesn't apply if you run the crawler on the same domain as the script is being executed on. 


Give it a try! Would be cool to know how well it works (or how badly it fails)






On Thu, Mar 17, 2016 at 8:15 AM -0700, "Hristo Dimitrov" <notifications@github.com> wrote:












Is it possible? Can I use node-simplecrawler with browserify or Webpack on the client side? I'd like to use the users to crawl the websites and pass the data to a server ...

**Comment by cgiffard** [comment]
Sounds like a fun project — I'm curious to know what the outcome is!

**Comment by hristod** [comment]
@fredrikekelund I didn't think about the type of requests being different, which does change things... I will have to find another way to do what I wanted to... What I was trying to do was use the clients as scraping agents instead of scraping everything from the server... There are other options - like proxies - but this looked like a very good idea - outsourcing some of the work to the client and getting the proxy for free :)

**Comment by fredrikekelund** [comment]
Closing this as this isn't really an open issue. But curious to know if you ever tried to use it in the browser, @hristod? :)

**Comment by hristod** [comment]
Hey. I haven't tried it yet, but hopefully will start testing in the next month or so :) I will try to keep you updated :)
