### ISSUE TITLE
only fetch html content without any resources

### ISSUE THREAD

**Issue by hbakhtiyor** [cgiffard/node-simplecrawler#266]
i want only fetch html content without any resources, like js, css, images, pdf, ....
how to do?

**Comment by fredrikekelund** [comment]
First, set `crawler.supportedMimeTypes=["text/html"]`, then set `crawler.downloadUnsupported=false`. You can also write a fetch conditions that prevents URL's that end in eg. ".jpg", ".css", ".js", ".pdf" or ".png" in order to not even try and fetch those URL's (for resources that are discarded based on mimetypes, the crawler still has to fetch headers to determine what mimetype it's about to receive)

**Comment by hbakhtiyor** [comment]
thanks,

btw, `supportedMimeTypes` option accepts regex object, also need to accept string too, it will be more flexible.

**Comment by cgiffard** [comment]
You match anything with a regex you can match with a string. :)
