### ISSUE TITLE
Crawler hangs right before the end of the article

### ISSUE THREAD

**Issue by thecameronjones** [cgiffard/node-simplecrawler#270]
I am using this software to crawl Wikipedia as a test. The repository with my code can be seen [here](https://github.com/thecameronjones/crawler). I am using a crawler depth of 2 so it will only read the articles linked to the main one initially specified. Right before it finishes reading the end of the initial article, it will hang and the `complete` event won't fire. Also, there will still be a couple links left at the end of the article that it didn't crawl. I have tried many times to debug my code and fix this issue but I have had no success. Does anyone know if my code is the issue or if it's a legitimate bug?

**Comment by fredrikekelund** [comment]
It looks like you forgot to call toString on the buffer [here](https://github.com/thecameronjones/crawler/blob/master/app.js#L31). Also keep in mind that if you load the response body as a cheerio instance twice and modify one of them, that won't affect the other instance. You can load it once and attach the instance to the current queueItem to be able to pass it between event listeners and discoverResources. Just remember to unset it when you're done so it can be picked up for GC. Otherwise your app will be using a lot more memory than necessary

**Comment by thecameronjones** [comment]
Thanks for the reply. Calling `toString` does not seem to solve the problem. It still hangs a couple links before it's supposed to stop. Also, as I am a novice using cheerio (the jquery-like format) and optimizing memory usage in code, could you be _more_ specific about what you mentioned? Although the primary issue is still the crawler hanging. @fredrikekelund

**Comment by cgiffard** [comment]
Hey! Would you mind adding this code to your crawler and letting me know what the output is? Often, the crawler might be doing something else that you won't see if you're only listening to `fetchcomplete`. (For now I can't rule out that it isn't a bug, but the output of this would help there too.)

```js
    var originalEmit = crawler.emit;
    crawler.emit = function(evtName, queueItem) {
        crawler.queue.complete(function(err, completeCount) {
            if (err) {
                throw err;
            }

            crawler.queue.getLength(function(err, length) {
                if (err) {
                    throw err;
                }

                console.log("fetched %d of %d — %d open requests, %d open listeners".green,
                    completeCount,
                    length,
                    crawler._openRequests,
                    crawler._openListeners);
            });
        });

        console.log(evtName, queueItem ? queueItem.url ? queueItem.url : queueItem : null);
        originalEmit.apply(crawler, arguments);
    };
```

(@frederikekelund I should add this to the troubleshooting section in the readme.)

**Comment by thecameronjones** [comment]
Would you like me to paste it into a file and send it to you? The output will be **very very very** long... @cgiffard

**Comment by cgiffard** [comment]
@thecameronjones Gist it and link here, if that's ok. :)

**Comment by cgiffard** [comment]
The important part is the lines emitted before the hang, too — so if after pasting that in you're still seeing a hang, it might be helpful just to grab 100 or so lines prior to it.

**Comment by thecameronjones** [comment]
[This](https://gist.github.com/thecameronjones/747f34041590e5541ff83b87f10c3dc7) is the link, but first I have a couple things to note: First, I had to stop running the app early because I was concerned how much text was going to be outputted and how long it would take. Secondly, I found that the `depth` parameter went past `2`, which is the depth I specified in the setup. Finally, a lot of the links logged were those of Wikipedia articles that had little or not much to do with the initial one set. This leads me to believe that either the code you told me to paste in caused that or I have a larger issue in my code. @fredrikekelund

**Comment by thecameronjones** [comment]
It's going to take hours/days to finish because it's still on `depth: 3` and I don't know if that is the limit or if the setup didn't work.

**Comment by cgiffard** [comment]
Ah, I just noticed a mistake in the code — it expects 'colors'. Pull off the `.green` and try again (my apologies for that!)

I don't understand why that would change the depth setting, but it does cause the 'undefined' at the start.

**Comment by thecameronjones** [comment]
Still, from the start, it logs `queueduplicate` that have a `depth` of `3`. For example, `queueduplicate { protocol: 'https',
  host: 'en.wikipedia.org',
  port: 80,
  path: '/wiki/California',
  uriPath: '/wiki/California',
  depth: 3 }` I'll let it run for a while this time and send you the gist _if_ it hangs or after 10 minutes or so. @cgiffard

**Comment by cgiffard** [comment]
`queueduplicate` means it's already queued that resource for downloading, presumably at a lower queue depth. So that doesn't necessarily mean the queue depth is being exceeded.

**Comment by thecameronjones** [comment]
What confuses me is that those articles are sometimes _completely_ unrelated to SpaceX which was the original topic. Some of those `queue duplicate` are things that aren't linked inside that article and that aren't ever fetched. **New Information:** After running your logging software (which has definitely affected how the program runs in some large way) I have watched it finish queuing things and start fetching them. Right now it is logging: `fetchheaders https://en.wikipedia.org/wiki/Low-technology
fetched 1167 of 37879 — 5 open requests, 0 open listeners
fetchheaders https://en.wikipedia.org/wiki/Mature_technology
fetched 1169 of 37879 — 4 open requests, 0 open listeners
fetchstart https://en.wikipedia.org/wiki/Technocapitalism`. As you can see it has queued 37879 articles which _definitely_ isn't a depth of 2. Without your added code my program logs max 100 articles.

**Comment by cgiffard** [comment]
Well that is certainly unusual. I don't understand how that code would make the crawler fail to respect max-depth, but I'll look into it!

**Comment by thecameronjones** [comment]
Thanks! It really is confusing me too... It might be helpful for you to clone the repo and see for yourself. @cgiffard

**Comment by fredrikekelund** [comment]
I'm not sure why this would cause the maxDepth setting to not be respected, and we need to change this in the README, but you need to call `crawler.cleanExpandResources(resources, queueItem)` in the discoverResources method before returning the resources array. It could be that this is what's causing the problem!

**Comment by cgiffard** [comment]
I wonder if that requirement is itself confusing. I'll look over the code tonight.

**Comment by fredrikekelund** [comment]
Yeah, I think it probably is, and would be easy to move out of that method. Cool!

**Comment by cgiffard** [comment]
As an aside to the issue experienced by @thecameronjones, my old colleague from my previous day job sent me an email to say:

> Hi mate, sorry i forgot to reply back on friday. i tested all our sites with the master and it worked like a charm.
> Thanks for fixing it

So I think we must be good (apparently it the bug was reproducible every time.)

**Comment by thecameronjones** [comment]
Would you mind letting me know how I may resolve this problem by implementing `crawler.cleanExpandResources(resources, queueItem)` or by updating link discovery on the README? @fredrikekelund @cgiffard

**Comment by fredrikekelund** [comment]
It's very simple, I submitted a PR to your project for it! https://github.com/thecameronjones/crawler/pull/1

**Comment by thecameronjones** [comment]
It turns out that it still hangs before the end as it always has. Could you clone the code, run it, and make sure I am doing things right? @fredrikekelund

**Comment by fredrikekelund** [comment]
And still fetches as many pages? I can have a look at it, but I don't have time right away. Try removing the custom discoverResources method altogether once to see if that's what's causing the issue or not

**Comment by cgiffard** [comment]
Are you using 0.6.2? Try using the code off master branch.

**Comment by thecameronjones** [comment]
I am updated to the latest version and even when removing the custom discovery code, it hangs (but at a different location farther down in the article). @fredrikekelund @cgiffard

**Comment by cgiffard** [comment]
Just to confirm, is that 0.6.2? Or the code from `master` branch, which is not yet available on NPM (we'll be cutting an 0.7 release soon — sorry for the hassle!)

**Comment by thecameronjones** [comment]
Yes, I downloaded from `master` and ran `npm install --save` in the module directory. @cgiffard

**Comment by thecameronjones** [comment]
Okay. I may have misdiagnosed my issue. It isn't "hanging", but it is actually not firing the `complete` event. Even when running **simple** code like [this](https://raw.githubusercontent.com/thecameronjones/crawler/master/simplecode.js), it still doesn't fire the correct event handler. Am I missing something very obvious? @fredrikekelund @cgiffard

**Comment by thecameronjones** [comment]
Alright, thanks so much for your help. It's a very useful package. @cgiffard

**Comment by fredrikekelund** [comment]
I've tested your code @thecameronjones, and the problem is due to the `fetchWhitelistedMimeTypesBelowMaxDepth` logic that dictates that resources at the maximum depth will still be scanned for resources, in order to be able to fetch those resources below the maximum depth if they have the correct mime type (which we need to fetch them to determine).

This implementation is a little weird in that even if you haven't enabled `fetchWhitelistedMimeTypesBelowMaxDepth`, this logic will still kinda apply, it's just that the resources below the maximum depth won't fire any `fetchcomplete` events.

When testing your code, this is what caused the crawler to hang (or, as you noted, not really hang, but actually keep fetching pages), because after having fetched the 300-something resources within the 2 first depth levels, it had in total discovered something like 65000 pages, which it now was churning through in order to determine if it was allowed to emit `fetchcomplete` events for them.

I've been looking at overhauling this logic for some time, and I just bumped it a bit on my list of priorities. In 1.0.0, `fetchWhitelistedMimeTypesBelowMaxDepth` will be gone, and the crawler will behave as expected in your scenario. Those who need a `fetchWhitelistedMimeTypesBelowMaxDepth` setting will have an API that enables more custom logic. See #249 for more details.

So what to do about your problem in the meantime? You can add this snippet to your code (I've submitted a PR for you as well):

```js
crawler.addFetchCondition(function(parsedURL, queueItem) {
	return parsedURL.depth <= crawler.maxDepth;
});
```

**Comment by cgiffard** [comment]
I think this is a perfect demonstration of why adding too much complex logic to the core crawler can back to bite us later. :)

I think we should add a `deprecated` feature which warns when people use things we intend to deprecate. I reckon for `0.8`, since 0.7 is already getting pretty big and stuff is backing up.
