### ISSUE TITLE
Better documentation of discoverRessources specific options

### ISSUE THREAD

**Issue by lgraubner** [cgiffard/node-simplecrawler#277]
There are some options which only affect the crawler if the default `discoverRessources` function is used. If a custom function is provided those options become obsolet. It might be confusing to set those options which do nothing in that case. The options I found so far are:

* discoverRegex
* parseHTMLComments
* parseScriptTags
* stripQuerystring

So I suggest to point that out in the docs and maybe group them. Anyway it's not ideal to provide options for interchangable parts. I could think of a single option which consists of an object, which is passed to the `discoverRessources` function.

**Comment by fredrikekelund** [comment]
Agree that it'd be a good idea to highlight hese properties on the README. But I don't think `stripQuerystring` is used in `discoverResources`(see [this](https://github.com/cgiffard/node-simplecrawler/blob/master/lib/crawler.js#L663)).

I'll have to give some thought to the idea of grouping the discoverResources related options in an object. Might actually be a good idea, just for claritys sake. If we passed it to the `discoverResources` function, then different implementations of that method could reuse those options as well. I'm not sure people would actually be too interested in doing that, but it would promote more shareable `discoverResources` implementations, which is good

**Comment by lgraubner** [comment]
The `stripQuerystring` option is indeed not affected. Thanks for thinking about it.

**Comment by fredrikekelund** [comment]
I just submitted a PR to fix #278 (#315), and I realized that it affects this issue since it uses the Crawler#respectRobotsTxt setting in the Crawler#discoverResources method to check whether it should look for a `<meta name="robots" value="nofollow">` tag.

The problem arises from that with regards to this issue is that Crawler#respectRobotsTxt isn't used only to control whether to respect the nofollow meta tag, but also the rules in robots.txt. We could use a different setting to control whether to respect nofollow meta tags, but I'm kind of leaning towards not doing that, since robots.txt and the meta tag complement each other as two parts of the same solution for website owners. And in any case, we have already cleared this up in the documentation. But I'm not 100% sure yet. What do you think, @cgiffard and @lgraubner?

**Comment by cgiffard** [comment]
I think it should probably be one setting for both. I reckon we'll only confuse people by adding two, and the number of times somebody would want to respect one but not the other must be vanishingly small — I can't think of a good use case.

**Comment by fredrikekelund** [comment]
Fair point, let's stick to the single setting then! I guess that also means we only highlight the Crawler#discoverResources related properties in the documentation, we don't put them in a separate namespace?

**Comment by cgiffard** [comment]
I think we just keep it simple for now. Refactoring opportunities will present themselves as we get a better idea for how people use it in practice and what features they're utilising. :)

**Comment by fredrikekelund** [comment]
Cool! I'll merge #315 tonight then and close this issue - we'll stick to just highlighting the affected properties in the documentation

**Comment by lgraubner** [comment]
+1 for single option. There is no reason to set the options different.
