### ISSUE TITLE
Missing fetchcomplete

### ISSUE THREAD

**Issue by xverges** [cgiffard/node-simplecrawler#287]
For queued items in the last allowed depth, I am missing the `fetchcomplete` event. I don't know if I misunderstand something, but, after getting a `fetchstart` and a `fetchheaders`, I am expecting a fetch completion notification...

https://github.com/cgiffard/node-simplecrawler/blob/9131f384c6a8159c9b95e83e645eff4d7c090f5f/lib/crawler.js#L1270

(BTW, thanks from a happy user!)

**Comment by fredrikekelund** [comment]
This sounds like unexpected behavior that could be due to the current logic around `crawler.fetchWhitelistedMimeTypesBelowMaxDepth`. Please see https://github.com/cgiffard/node-simplecrawler/issues/270#issuecomment-210459838 for more details.

This functionality is due for an update as soon as we get around to it!
