### ISSUE TITLE
Why does a fetchheaders get emitted with a higher depth than maxDepth?

### ISSUE THREAD

**Issue by ibexofentropy** [cgiffard/node-simplecrawler#289]
I want it to stop at say depth 2, but it calls `complete` after `fetchheaders` has been called multiple times.

**Comment by fredrikekelund** [comment]
This is due to the current logic around `crawler.fetchWhitelistedMimeTypesBelowMaxDepth` which dictates that resources below the maxDepth that have a whitelisted content-type header will still be fetched. See https://github.com/cgiffard/node-simplecrawler/issues/270#issuecomment-210459838 for more details and a workaround.

This behavior has caused quite a bit of confusion, and is due for a change in the upcoming release.

**Comment by ibexofentropy** [comment]
How would I make it not emit a `fetchheaders` above `maxDepth`?
Changing `crawler.fetchWhitelistedMimeTypesBelowMaxDepth` `and crawler.whitelistedMimeTypes = [];` didn't seem to work

**Comment by fredrikekelund** [comment]
The crawler still fetches resources below maxDepth even if `fetchWhitelistedMimeTypeaBelowMaxDepth` is false. Not the best solution, but the option is about to go away altogether. For now, do this:

```js
crawler.addFetchCondition(function(parsedURL, queueItem) {
    return parsedURL.depth <= crawler.maxDepth;
});
```
