### ISSUE TITLE
Schedule link fetching by HTML condition

### ISSUE THREAD

**Issue by ivan-kleshnin** [cgiffard/node-simplecrawler#322]
Now we can analyze HTTP stuff to keep or prevent some link from fetch scheduling via **fetch conditions**.

Can I command a crawler to ignore, say, all links except found in specific HTML blocks?

There are a lot of cases where URL contains no patterns so it can't be used as a factor. And the only thing which helps is CSS selector of referring link ascendants.

Should I use [this feature](https://github.com/cgiffard/node-simplecrawler#manually-adding-to-the-queue) or is there simpler approach?

**Comment by cgiffard** [comment]
The best way to do this would be to write your own link discovery function, and just select those blocks yourself, rather than keeping simplecrawler's default method — which selects everything it can — and then trying to prune the unwanted resources out later.

See [Link Discovery](https://github.com/cgiffard/node-simplecrawler#link-discovery) for more information:

```js
crawler.discoverResources = function(buffer, queueItem) {
    var $ = cheerio.load(buffer.toString("utf8"));
    
    // Here's where you'd filter just to the blocks you wanted.
    return $("a[href]").map(function () {
        return $(this).attr("href");
    }).get();
};
```

**Comment by ivan-kleshnin** [comment]
That's what I wanted. Thank you!

**Comment by cgiffard** [comment]
Glad to have helped. Good luck with your project. :)
