### ISSUE TITLE
[INFO] Only fechts without download

### ISSUE THREAD

**Issue by KartoffelToby** [cgiffard/node-simplecrawler#331]
Is it possible to only return the URLs without downloading the pages?

**Comment by fredrikekelund** [comment]
Short answer: yes. 
Long answer: you can't crawl an entire site without actually looking through the response bodies of the pages on it, since that's where you'll find the next URL's to crawl.

But you can save the URL's that you receive via any of the events however you like. Perhaps `discoverycomplete` would suit your needs? You can also use download conditions if you want to fetch only the headers of certain pages. If you need more specific help, maybe you can let us know some more about your use case
