### ISSUE TITLE
Is there any way to share the Quene between multiple crawlers in a PM2 cluster

### ISSUE THREAD

**Issue by sherkhanz** [cgiffard/node-simplecrawler#338]
Hi, 

Thanks for the awesome crawler. Its my first time dipping my feet into crawling and simple crawler is the perfect match. I want to distribute the work load on multiple crawlers and I am using PM2 for it. I tried implementing this package https://github.com/lzrski/node-simplecrawler-queue-mongo unfortunately it didn't worked. I have configured it but neither there is any thing in queue nor in error log. 

So is there any way through which I can share the queue among multiple crawlers so that if two crawlers receive the same url, they should not crawl it two time.  
Any help will be much appreciated.

Thanks :)

**Comment by fredrikekelund** [comment]
Hey, glad to hear you're finding simplecrawler useful! Making it simple to run simplecrawler in a distributed manner was one of the original ideas of the simplecrawler architecture. This hasn't really been put into practice very much though, and until the 1.0.0 release a couple of months back, the queue interface didn't officially support async queue implementations (which is needed if you want to have some kind of database to back a cluster of crawlers).

There's still some work to be done to sync cookies (#313) and caches between crawler instances, but those features aren't critical for all use cases. So if you really want to run a crawler cluster, you could write your own queue implementation! The interface is pretty simple and quite well documented in [the code](https://github.com/cgiffard/node-simplecrawler/blob/master/lib/queue.js).

I should say however, that running the crawler in a distributed manner isn't always necessary if all you're looking to do is increase the speed of your crawl. Have a look at increasing the `maxConcurrency` and `interval` parameters if you want to see how fast you can go (but beware that the faster you crawl a site, the more likely they are to take notice of you, and possibly block your IP).

I hope that we, the simplecrawler maintainers, will release one or two such queue implementations, but outside contributions are more than welcome!

**Comment by sherkhanz** [comment]
Thanks @fredrikekelund  For such a detailed reply. We are actually using this crawler to run against our own 100+ sites multiple times per site a week. So that will not be issue. I am setting the system in such a way that our developers will just submit the domain and the configuration (pages per second, interval, concurrency etc)through a form and it will get submitted to a script running the crawler as PM2 process.  I guess setting these variable dynamically will set them only for the submitted domain . Am I right on this one?

For the Queue, I am trying to build one if there is no solution available. A few guys have wrapped simple-crawler in their own packages claiming a shared Queue through a database but I was not able to put them to work as most of them are quite old. 
The limiting factor is that I am a developer from php and javascript technology. A strong grip of JS helped me grasp the basics of nodejs in few days but I am still struggling with some parts. If you can give me a rough idea on a best practice to implement such a system, I will surely give it a try or get someone do it. And will like to submit a pull request after optimizing it for direct integration with simple crawler. 

Thanks once again 👍

**Comment by fredrikekelund** [comment]
@sherkhanz cool! Then I guess you don't need to do any rate limiting. Yeah, I don't know exactly how you have your system set up, but the `interval`, `maxConcurrency` etc properties only apply to the one crawler instance you set them on.

Sure, so what I'd look into for writing a queue like that is to first pick a database to back the queue. The crawler will be hitting the queue quite often: every time it asks for a new URL to fetch, every time it adds an item to the queue and every time it updates a queue item. So since performance is a pretty important factor, I'd advice you to use some NoSQL database, maybe MongoDB. Then, I'd pick some type of ORM-like library ([mongoose](https://www.npmjs.com/package/mongoose) is the most populat one for Mongo) to make it easy to work with the database. After that, I'd take the existing queue implementation and start swapping out each method to work with a database instead. The queue interface is pretty simple, there aren't that many methods and they're all pretty narrow in their scope. You don't even have to implement all of the existing ones - `FetchQueue#min`, `FetchQueue#max`, `FetchQueue#avg` are optional, and `FetchQueue#freeze` and `FetchQueue#defrost` won't make much sense if you're already using a database. And once again, the code is pretty well documented, it's just that all the documentation is in the code only (we haven't generated any HTML from it yet).

I should mention that even though the basic pieces of a distributed architecture are in place, it isn't unlikely that you'll run into race conditions. One way to get around that might be to add a property to the queue items stored in the database that specifies which crawler instance is handling them. If you retrieve an item from the DB in `FetchQueue#oldestUnfetchedItem`, make sure that no other instance has already taken it, and that each crawler instance (or rather, your queue implementation, running in that crawler instance) updates the object in the database first thing, to avoid race conditions.

Feel free to hit us up with any specific questions you might have, I'll leave this ticket open so we can keep the discussion in here.

**Comment by sherkhanz** [comment]
Hi @fredrikekelund  I had somewhat the same idea. I was thinking of redis initially but as you have mentioned mongodb, I found a fork of orignal mongodb package for simple crawler here https://github.com/herkyl/node-simplecrawler-queue-mongo while the original one is here:  https://github.com/lzrski/node-simplecrawler-queue-mongo 

I installed a mongodb on the same ubuntu server. create a database and made connection through 

  mongoose.connect("mongodb://127.0.0.1:27017/queue"); the test for connection 

 console.log(mongoose.connection.readyState);

returns 2 which I guess is connected. Now when I expose MongoQueue.js API to crawler.queue I get error method db.get() not found at line 12 in MongoQueue.js 

Now when I read that file, I found out that the first repository had  recent commits a year ago and as compared to original package where two attributes were passed to the MongoQueue function, now 3 are passed. 

Old Version: 

  module.exports = MongoQueue = (function() {
    function MongoQueue(mongo, crawler) {
      var event, eventstates, query, setEventHandler, status;
      this.crawler = crawler;
      console.log("Initializing mongo queue for " + this.crawler.name);
      this.Item = getItem(mongo, this.crawler.name);
      this.updateStatus = function(item, status) {
        console.log("" + status + " \t " + item.url);
        item.set({
          status: status
        });
        return item.save(function(error) {
          if (error) {
            throw error;
          }
        });
      };


New Version:

 module.exports = MongoQueue = (function() {
    function MongoQueue(mongo, db, _at_crawler) {
      var event, eventstates, query, setEventHandler, status;
      this.crawler = _at_crawler;
      // console.log("Initializing mongo queue for " + this.crawler.name);
      this.hosts = db.get('hosts');
      this.Item = getItem(mongo, this.crawler.name);
      this.updateStatus = function(item, status) {
        item.set({
          status: status
        });
        return item.save(function(error) {
          if (error) {
            throw error;
          }
        });
      };
      eventstates = {
        fetchstart: 'spooled',
        fetchcomplete: 'fetched',
        fetcherror: 'error',
        fetchredirect: 'redirected'
      };


The orignal document suggest passing the MongoQueue to the crawler like this:

     crawler.queue = new Queue(
            mongoose.connections[0],
            crawler
        );

I don't know what third parameter should I pass for db or mongo as one is the connection but what's the other for. Can you have a look around and kindly guide me on this? I though it will be better if I can get it to work as the time that will be spent on reinventing the wheel can be spent on improving on what's already done and making it work out of the box.

**Comment by sherkhanz** [comment]
I was trying to fix the code of the mongoQueue and now its not giving any error.  I am using this :

```
  var Crawler = require('simplecrawler');
  var Queue    = require('./MongoQueue');
  var mongoose  = require("mongoose");

  mongoose.connection.on('error', function (err) {
           console.log('error connecting');
           console.log(err);
  });
  mongoose.connection.on('open', function () { console.log('Connection opened')});
        mongoose.createConnection("mongodb://127.0.0.1:27017/queue",function(err) {
            // if (err) console.log(err); throw err;

            if(mongoose.readyState===1) {
                next();
                console.log(err);
     }
     else {
            console.log(err);
            return err;
      }
  });
 

 var crawler = Crawler("http://example.wordpress.com");
crawler.userAgent= "Custom Bot";
crawler.name  = 'radzimy-co';
crawler.queue = new Queue(
            mongoose.connections[0],
            crawler
        );

  var dataHolder = {'url':{},'latency':{},'downloadTime':{},'contentLength':''};
        var i = 1;
        var b=0;
        crawler.on("fetchheaders", function(queueItem, responseObject) {
            dataHolder['url'][i] = queueItem.uriPath;
            dataHolder['latency'][i] = queueItem.stateData.requestLatency;
            dataHolder['downloadTime'][i] = queueItem.stateData.downloadTime;
            dataHolder['contentLength'][i]= queueItem.stateData.contentLength;
            i++;
            console.log(queueItem.uriPath+' => '+queueItem.stateData.contentType);

        }).on("fetchComplete",function(queueItem, responseBuffer, response){
            dataHolder['html'][b]= responseBuffer.toString();
            b++;
            if(b>=501) {
                crawler.queue.freeze("mysavedqueue.json", function () {
                    process.exit();
                });
            }
        }).on('complete',function(){
                var fs = require('fs');
                var randomName = Math.random().toString(36).substring(7);
                fs.writeFile(randomName+"urls.html", JSON.stringify(dataHolder) , function(err) {
                    if(err) {
                        return console.log(err);
                    }
                    // console.log(queueItem.uriPath);
                    // return false;

                });

            });
        var conditionID = crawler.addDownloadCondition(function(queueItem, response) {
            console.log('ALLURLS =>'+queueItem.uriPath);
            return (
                queueItem.stateData.contentType.indexOf('text/html') !== -1 &&
                queueItem.uriPath.indexOf('wp-content') == -1
            );

        });
        crawler.interval=100;
        crawler.maxConcurrency=10;
        crawler.stripQuerystring=true;
        crawler.decodeResponses=true;
        crawler.start();
   
```

But the strange thing is that Queue is not working. No page is crawled and no error is given.  Does the simplecrawler has tests for Queue? The npm dependencies I have downloaded does not have one. I was thinking to run those tests against the mongo Queue and see if I can find the bugs.

**Comment by fredrikekelund** [comment]
From looking through the code of the fork you linked, it doesn't look like it's compatible with simplecrawler 1.0.0 and up. I can't vouch for the rest of the code, but one obvious problem is the way it handles queue item states, which is no longer applicable. With the current version of simplecrawler, queue implementations should instead implement the FetchQueue#update method.

Rather than using that repo, I'd advise you to write your own queue implementation from scratch. You can reuse parts of existing implementations, but it would be better to pick up those parts explicitly, rather than to work with an existing base that you're not familiar with. 

Alternatively, you might want to consider if you really need the crawler to run in a distributed cluster? If you're not looking to crawl the same site with multiple crawler instances at the same time (which is mostly only necessary if you're trying to get around some rate limiting - which isn't a problem for you - or crawling a *huge* site), then there's nothing stopping you from storing data for the individual queue items in a database, only that you perform the save operations in the crawler's event handlers (like fetchcomplete etc) instead of in the queue. I've worked with a system where I did this, and it worked great! That's the beauty of node as well, that such calls to the DB are asynchronous, meaning that the crawler will keep fetching pages while I'm saving stuff in the database, so performance doesn't suffer. Maybe you're already familiar with that, but since you said that you're new to node, I just thought I'd expand a bit on the options you have available :)

**Comment by sherkhanz** [comment]
Usually one crawler is enough for a site and as PM2 process auto load balance the any request to the port exposed. So every-time I submit a new url , It will get to a new process in PM2. I can control not to send a url twice to two processes. But what's the problem is that when I collected the urls from multiple processes running an instance of the crawler, there was difference in the number of URLs. From 15 to 20 urls. So I though it might be better to share the Queue and maximize the Link discovery. 

For now, I will follow your words for optimizing a single crawler for a single site in a PM2 process. Later on when the system is in production then I can take time and write the API for Queue to use Mongo,


Thanks ;)

**Comment by fredrikekelund** [comment]
Closing this for now, let us know if you need more help, @sherkhanz!
