### ISSUE TITLE
Bad Performence in Big Sitemaps (item - discovery)

### ISSUE THREAD

**Issue by geramy92** [cgiffard/node-simplecrawler#364]
## What happened?
If you crawl bigger pages then they have mostly a sitemap or linked pages with a huge number of links. In my case we are talking about 400.000 Links on one sitemap. I know that this is not a normal number but it shows a big problem of simplecrawler that is also happen on smaller sitemaps which have around thousands of links. The actual discover functionality of simplecrawler is completely syncronous and blocks the complete nodejs process. Additionally it uses a lot of .map and .reduce functions. Which are quite slow.

I tried to debug it and could found that the main problem is the function "cleanExpandResources"  (see https://github.com/cgiffard/node-simplecrawler/blob/master/lib/crawler.js#L817). More specific: The reduce on line 829.

## What should have happened?
This functionality should be replaced by async functions. There are packages or examples (I do not know what is the best here) to do that. So that the main NodeJs Process is not blocked anymore by this sync approach.

## Steps to reproduce the problem
See Text. 
I cannot provide here my sitemap because it is within a private network. But I think it is easily to create such a file by adding a lot of Urls (or just use a google sitemap on the internet that has a lot of urls.)

**Comment by fredrikekelund** [comment]
Thanks for leaving a report, @geramy92! I don't believe that node.js has a concept of multithreading that's flexible enough to support a situation like that. This is a core point about node.js - I/O is asynchronous (multithreaded), but all computation operations run in a single thread.

I'm curious to see what kind of performance hits you're taking with that many links, though. While we could refactor `Crawler#cleanExpandResources` with the aim of improving performance, it is a somewhat complex method and it would be nice to know what kind of gains we stand to make performance wise.

If you have a concrete suggestion for how to accommodate this behavior, I'm all ears! But I think that generally, modules that deal with asynchronicity will be *introducing concepts to help deal with operations that are asynchronous by default*, those modules *won't enable us to simply make code asynchronous*.

**Comment by geramy92** [comment]
I mean packages like https://github.com/jonschlinkert/async-array-reduce or https://github.com/caolan/async  they provide completely custom implementations instead using reduce. 

I didn't try it out right now, but if you want I can try some different options out or try write something custom but they show how you could solve it in this case.

**Comment by fredrikekelund** [comment]
Those kinds of modules were what I was referring to when I wrote that most "async*" modules will help *deal with asynchronicity*, they won't *introduce asynchronicity*. So basically, those modules are only useful if you have to do network or disk access from within a map/filter/reduce callback, they won't run the callback in parallel for each item in the array.

**Comment by geramy92** [comment]
you are right, but I am completely unsure how you could solve it like you wanted the async. 
My problem with that is more less this:
- It blocks the single thread during execution of Array.reduce (that can be solved with such packages or a simelar implementation because they something like an recusive callback based implementation.
Additionally to that JS function Array.reduce is 70% slower than doing the same as a loop out of the box (there are several performence tests on the internet)

But to have everything within reduce in parallel.... I have no solution.

By the way multithreading is not existing that is correct, but nodejs provides two options to do that. First is multiprocessing with childprocesses or webworker threads. But is much more complicated and would I think require much more changes.

**Comment by fredrikekelund** [comment]
Alright, well let's discuss the possibility of refactoring the array methods in `Crawler#cleanExpandResources` into a for loop. I had to Google some benchmarks to get an idea of the performance differences there, and while it does look like for loops are faster, my guess is that if that particular reduce method is slow, it's because we construct uri.js instances from all URL's inside of it.

You're very welcome to submit a PR if you want to see how much performance could be gained from switching over to for loops, I'm definitely open for it!

**Comment by cgiffard** [comment]
I think to some extent the solution here is a distributed queue. We can improve the performance of the discovery operation to a point, but the current discovery function *isn't supposed* to be the highest performing thing in the world — I've always emphasised maintainability and understandability rather than juicing it for every available cycle. The intention is that if you've got a specific requirement for discovery, you throw in your own function, allowing the general discovery function that exists to be a reasonable default for most cases.

Also consider that node's unfortunate excuse for IPC blocks **hard** because of serialisation overheads. Doing discovery off-thread is probably less efficient than just spooling up more queue workers and hanging them off the same distributed queue. (Except perhaps in the memory stakes.)

That said, if there are key ways we can improve performance that aren't going to make the code opaque in the process, I think it's reasonable to consider getting those in (though I would emphasise that the default discovery function is really designed to be a starter — something you replace when you know how you're going to structure your crawl.)

**Comment by geramy92** [comment]
As an Information: For me it would be enough to know, that it is not blocking completely the main process (I tried also to improve performence but until now it ends up in a really crazy stuff that will not be good approach).  In this way you could use simply "async.reduce" - from package async what you already have. I have an working implementation for that already that is minimum as fast as before but doesn't block the rest of the programm completely. Means in my case I have a timer in background that is doing some stuff and this can then execute by default without being blocked. (I will provide a PR on Monday then you can decide)

@cgiffard the thing is, that in our case the default link discovery is quite nice except the cleanExpandResources function and this function is called (as far as I read from your code) after the discover link function that can be overwritten like mentioned here: https://github.com/cgiffard/node-simplecrawler#link-discovery 
And to copy a lot of code only to change that... is in my eyes not really a good solution but like mentioned I will provide a PR on Monday then you can decide together if yes or no. ;-)

**Comment by geramy92** [comment]
Yeah I noticed that I can not provide a Pullrequest without changing a lot. The reason is simply it will delay some functionality to more later ticks. Means it breaks the tests and additionally I am not sure about the event that is triggered there. 
For me I changed our code to run in real parallel with a separate process, so that it doesn't block it anymore (either simplecrawler process is blocked)

**Comment by geramy92** [comment]
Btw. the code I had on Pullrequest is working as replacement but not for allow process like mension in my previous comment

I tried running our process with my code from my closed Pullrequest and it is much faster. 
So I only wanted to mention that. Maybe you are still interested. The only thing I did is to replace Array.reduce with async.reduce and handle the callback with process.nextTick (to avoid infinite loop issue)

**Comment by fredrikekelund** [comment]
Thanks for spending the time to look into this @geramy92, but I don't think we'll want to introduce changes where Crawler#cleanExpandResources doesn't process all items that's passed to it at once. I'm still a bit surprised to hear that you're seeing such bad performance there however.

Are/were you running multiple crawlers in the same process?

**Comment by geramy92** [comment]
we are not running multiple crawlers. We have just some side functions that are running in parallel (like updating some states in our API or checking some stuff etc.) that were blocked before on crawling that side map with about 400k links. But I extracted our side stuff into a separate process so that it can do it's stuff in real parallel.
