### ISSUE TITLE
Support for promises

### ISSUE THREAD

**Issue by Domiii** [cgiffard/node-simplecrawler#367]
First of all: Yes! I have seen the FAQ, and you argue that promises are not helpful or practical here, but here is a simple example of how promises can make for a much smoother ride.

Consider this random code sample from your README:

```js
var originalEmit = crawler.emit;
crawler.emit = function(evtName, queueItem) {
    crawler.queue.countItems({ fetched: true }, function(err, completeCount) {
        if (err) {
            throw err;
        }

        crawler.queue.getLength(function(err, length) {
            if (err) {
                throw err;
            }

            console.log("fetched %d of %d — %d open requests, %d open listeners",
                completeCount,
                length,
                crawler._openRequests.length,
                crawler._openListeners);
        });
    });

    console.log(evtName, queueItem ? queueItem.url ? queueItem.url : queueItem : null);
    originalEmit.apply(crawler, arguments);
};
```

Using promises, we could get something along the lines of:

```js
var originalEmit = crawler.emit;
crawler.emit = function(evtName, queueItem) {
    console.log(evtName, queueItem ? queueItem.url ? queueItem.url : queueItem : null);
    
    return Promise.resolve(originalEmit.apply(crawler, arguments))
    .then(function() { return Promise.all([
        crawler.queue.countItems({ fetched: true }) }),
        crawler.queue.getLength()
    ]); })
    .spread(function(completeCount, length) {
        console.log("fetched %d of %d — %d open requests, %d open listeners",
            completeCount,
            queueLength,
            crawler._openRequests.length,
            crawler._openListeners);
    });
};
```

You did not only [escape callback hell](http://jamesknelson.com/grokking-es6-promises-the-four-functions-you-need-to-avoid-callback-hell/), but you even get to do things you would not be able to do previously!

Note how in your previous version, you kinda had this awkward dangling call to `originalEmit` basically being cast aside and kinda running in parallel to the new `emit` handler? What if the other `emit` handler was also asynchronous and you needed it to finish first? This can now be achieved with promises. (But I guess, generally, in event handlers this should be a non-issue to begin with.)

You also get to do two things in parallel (e.g. `countItems` and `getLength`) and add sync points afterwards, without a hassle!

All in all, promises are pretty awesome at writing asynchronous code as though it was synchronous code. Looking forward to a cleaner, promisified version of this project! :)

PS: Above code would look even better in ES7, but I'm not gonna push it for now :P

**Comment by fredrikekelund** [comment]
Hi @Domiii! The code you're referencing is a snippet from the README meant to aid debugging. The only methods that could use promisification there are the queue methods, and they don't even perform any actual async work with simplecrawler's default queue implementation (the API just supports other queue implementations that would need to do async work).

If you use the queue methods heavily and would like a promisified interface to them, I suggest using [Bluebird's](http://bluebirdjs.com/) [promisification functionality](http://bluebirdjs.com/docs/api/promisification.html) (which you're probably already familiar with). And as for the Crawler's interface, I don't believe promises will bring much to the table, since we use an event driven API.
