### ISSUE TITLE
SimpleCrawler finds no links

### ISSUE THREAD

**Issue by bjornwang** [cgiffard/node-simplecrawler#47]
I have an issue crawling http://kulturradet.no.

Every now and then, the crawler doesn't move past the front. Hooking into the discoverycomplete event, I can see that no links are found when this happens. I was baffled by this behavior, as oftentimes it finds 80 links. The HTML-code itself has not changed.

I spread some console.log(..) statemens in the crawler.js code, and found that the downloaded buffer seems garbled when this happens. When it works well, I get normal HTML from the page when i output the buffer. When the error hist, and no links are found, I get completely garbled output. This is both before and after the .toString(UTF8) conversion has been performed by the discover links-function.

A strange thing concerning this error is that there seems to be a timeout involved. The crawler stays in it's erroneous state for some 10-15 minutes, and then when I run it again, it finds links just fine again. Very strange. Downloading the page in a browser or using curl displays the HTML-code just fine without being garbled.

Any ideas on what can be causing this? What baffles me is the irratic behavior. Is there some caching involved, can a network error cause this so it's cached afterwards for example?

**Comment by robinparisi** [comment]
Hi,

I first considered opening a new issue then I found this one and I think it's related.
I'm currently experimenting on node-simplecrawler and try to determine if a page is compressed with gzip. Since 'Accept-Encoding' doesn't seem to be passed into headers (even if I have found this [issue](https://github.com/cgiffard/node-simplecrawler/issues/228)), I passed it by setting a custom header:

`crawler.customHeaders = {
    'Accept-Encoding' : 'gzip, deflate'
};`

Then, I'm able to determine if the page responds with gzip or not by parsing response headers. But, because response is gziped, simplecrawler doesn't seem to be able to perform the crawl.

Thanks in advance for your response.

**Comment by fredrikekelund** [comment]
Hi, thanks for reporting the issue @robinparisi! I think the cause of your problem might be that the change hasn't been released yet. The Accept-Encoding header is [set by default](https://github.com/cgiffard/node-simplecrawler/blob/master/lib/crawler.js#L384) in the latest `master`, but it's not in the 0.6.2 version.

We're looking at releasing 1.0.0 next, so we want to aggregate a good set of changes before the next release. I might look into backporting some of the new stuff into a 0.6.3 release before we go ahead with 1.0.0, though.

**Comment by robinparisi** [comment]
@fredrikekelund Thanks for the answer! I'm trying the latest version and just have one question. How do you plan to handle the response buffer when the page respond with gzip? Will buffer will be automatically unzip or we will need to do this manually?

**Comment by fredrikekelund** [comment]
Responses that are compressed are supposed to be extracted automatically. Keep in mind that if you get strange results from calling `toString` on the response buffer, that could also be due to the response encoding. Try setting `crawler.decodeResponses` to true to get back a string that's decoded based on the response's charset

**Comment by robinparisi** [comment]
When I set crawler.decodeResponses to true and use toString, I get the strange result. But if I set decodeResponses to false with the code below inside the fetchcomplete event, then I get the correct string :

```        
zlib.unzip(responseBuffer, (err, buffer) => {
    if (!err) {
        console.log(buffer.toString());
    } else {
        console.log(err);
    }
    process.exit()
});
```

**Comment by fredrikekelund** [comment]
If you are using the latest `master ` and are certain that you are getting response buffers in the fetchcomplete event that are compressed, then that's likely a bug.

decodeResponses will make it so that the fetchcomplete event gets a string instead of a buffer, FYI. And it's not related to decompression, but to character decoding. 

If your responses aren't automatically decompressed and the problem isn't character encoding, then it would be great if you could submit a new issue with details on what page you are crawling. Just please make sure to test thoroughly first :)

**Comment by robinparisi** [comment]
After some testing, I can't find the problem.

I've just opened this issue https://github.com/cgiffard/node-simplecrawler/issues/260

I hope I haven't done anything wrong since it's my first project with node.
