### ISSUE TITLE
Some questions about link discovery

### ISSUE THREAD

**Issue by bmoeskau** [cgiffard/node-simplecrawler#54]
I'm actually having a couple of issues, but first wanted to open a discussion before making changes and pull requesting anything.  There are two cases that are currently not working as I want:
- Hash links internal to a page should not be picked up as crawlable resources
- When I include Google Analytics, I end up with the faulty "links" of "https://ssl" and "http://www" which create false 404's

For hash links (e.g. `<a href="#foo">foo</a>`), IMO there's no reason for the crawler to pick these up, and I would personally have the crawler always ignore any link starting with #.  It's not a big deal, but in my case, I'm tracking stats around links closely and internal links needlessly clutter my stats.  However, if there is a valid use case for the crawler to discover internal links, then perhaps a config like `ignoreInternalLinks` would be useful (and I think should default to `false`, although perhaps that would be considered a breaking change).

For the second issue, the problem is that the GA script has this line:

```
ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
```

Because the crawler's `discoverRegex` property includes `/http(s)?\:\/\/[^?\s><\'\"]+/ig,` it unfortunately matches the GA script and results in those protocol fragments being "discovered" incorrectly.  For this, there are several potential fixes:
- Change the regex string to require at least one "." character in the url (not sure if that's 100% valid, but would at least fix this case), e.g. `http(s)?\:\/\/[^?\s><\'\"]+[.]+`
- Change the regex string to look for a more complete link syntax including "href=", e.g. `href=[\s\"\']+http(s)?\:\/\/[^?\s><\'\"]+`
- Declare the `discoverRegex` as an overrideable config on the crawler's prototype, rather than privately inside the discoverResources function

Personally, I would be in favor of implementing the third option for sure for max flexibility, but also implementing either 1 or 2 (or something similar) to avoid this case by default.  As it is, at the moment there's no easy way for me to fix this without editing the source directly or overriding that entire function.

**Comment by tomtom87** [comment]
Hi, also loving this crawler and just have a question about this idea:

```crawler.on("fetchcomplete",function(queueItem,data) {
    var $ = cheerio.load(data);
    $("[src],[href]").each(function(i,el) {
        crawler.queueURL($(el).attr("src") || $(el).attr("href"));
    });
});
```

I'm trying to do this currently but cannot get crawler within scope when inside the function, it's not available via this also. Any ideas? Thanks

**Comment by fredrikekelund** [comment]
@tomtom87 although you seem to describe a different issue, it seems one issue with your code is that you're trying to create a cheerio instance from a Buffer. The `data` argument is actually a Buffer, and so you need to call `var $ = cheerio.load(data.toString());`

The crawler should be accessible from your inner scope, but cheerio probably won't discover any links since AFAIK it can't load buffer. Let me know if this doesn't solve your problem!

**Comment by cgiffard** [comment]
Sorry, that was my fault for not testing my example first. :(

**Comment by tomtom87** [comment]
Hi guys, yes I actually found cheerio couldn't do it at all. I used responseBuffer.toString() to get the raw html out, and loaded that into jsdom. This has worked pretty well and with some regexp (last resort really didn't want to use this but had no choice, lost a day 'messing around' according to the boss) now my only problem remains here. I will explain.

I am trying now to add a url to the queue (by concatenating keyword tags and adding them to the search url) so that I can continue crawling. I am using

```javascript
myCrawler.on("fetchcomplete", function(queueItem, responseBuffer, response) {
var parsed = url.parse(queueItem.url);
var details = [
			"title",
			"thumbnail",
			"embedcode",
			"thumbnail_strip",
			"mp4_url",
			"tags"
		];
if(response.headers["content-type"] == "text/html; charset=UTF-8" && parsed.path.indexOf('watch') > 0) {
			console.log('Processing: %s', parsed.path);
			var jsdom = require("jsdom");
			jsdom.env(responseBuffer.toString(), ["http://code.jquery.com/jquery.js"],
				function (err, window) {
var $ = window.jQuery,
						$body = $('body'),
						embed_text = $body.find('#clip_text').text();
//get tags
					details["tags"] = window.$('.tagBoxContent:eq(2)').text();
					details["tags"] = details["tags"].replace(/<(?:.|\n)*?>/gm, '');
					details["tags"] = details["tags"].replace(/(\t|\n)/gm, '');

//add to the queue

    myCrawler.queue.add('http:', parsed.hostname, 80, '/search/?query='+details["tags"].replace(' ','+')); //myCrawler is not defined. How do I access it?
})
}
```

The problem is the myCrawler is not accessible..

**Comment by fredrikekelund** [comment]
I'm not sure your problem is that 'myCrawler' is undefined, I don't see anything overwriting it. It is possible that it's overwritten somewhere outside of the event listener however.

One issue though is that rather than calling myCrawler.queue.add, you should call myCrawler.queueURL(urlString, currentQueueItem)

**Comment by tomtom87** [comment]
@fredrikekelund  thanks I got it working now, I will try using the queueURL method, although .add is working good now. The problem was myCrawler went out of scope because I had it within the jsdom.. when I took it outside of that it was working again.

**Comment by fredrikekelund** [comment]
Ah, I see! Glad you found the issue!
