### ISSUE TITLE
HTML pages below maxDepth fetched

### ISSUE THREAD

**Issue by AndriusA** [cgiffard/node-simplecrawler#99]
Issue #77 says that "If the HTML page depth is greater than max depth, we will not fetch it and not discover resources on it" and while the latter is true, the former is not.

Running with a simple crawler:

    var Crawler = require('simplecrawler');
    var crawler = new Crawler("en.wikipedia.org", "/wiki/Fuel_economy_in_automobiles");
    crawler.maxDepth = 1;
    crawler.maxConcurrency = 5;
    crawler.downloadUnsupported = false;
    crawler.start();

Every page linked from the first one is downloaded

**Comment by rocco** [comment]
same here

**Comment by arve0** [comment]
Same here. Seems like version 0.3.10 is [published on npmjs](https://www.npmjs.com/package/simplecrawler), but the version in master is 0.3.11.

A simple console.log confirms the missing feature:
```
var crawler = new Crawler('localhost', '/', 3000);
console.log(crawler.filterByDomain);
console.log(crawler.proxyHostname);
console.log(crawler.maxDepth);
crawler.maxDepth = 1;
console.log(crawler.maxDepth);
```

**Comment by timbowhite** [comment]
@AndriusA is correct, resources one level above maxDepth are fetched, but are not "discovered", even on v0.3.11.

simplecrawler fetches every url one level above maxDepth to determine the MIME type of that url, so that things like css/js/img/whatever can be "discovered".

I forked a change that *never* fetches above maxDepth (see c83ab74fa42b3b3e35f4bd8ca82d33e64e580158).  This does have the consequence of not fetching a page's css/js/img/whatever if the page's depth +1 === maxDepth.

I think the best fix would be to examine the context of links on a page (ie. is the href in a `<link>`, is the src in a `<script>`, etc) when determining if they should be fetched, instead of just fetching everything.

**Comment by cgiffard** [comment]
Hi All — I've changed the behaviour of this feature in v0.5.0 as I agreed it was confusing. There's now an incredibly verbose switch called `crawler.fetchWhitelistedMimeTypesBelowMaxDepth` — set this to `true` to return to the old behaviour. Otherwise, the default behaviour should now match your expectations!
